import Head from "next/head";

import Hero from "@components/Hero";
import Footer from "@components/Footer";
import Card from "@components/Card";

export default function Home() {
  return (
    <div className={"py-0 px-8"}>
      <Head>
        <title>Next.js, Tailwind, Jest</title>
        <meta name="description" content="Generated by Create Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={
          "min-h-screen py-16 flex flex-1 flex-col justify-center items-center"
        }
      >
        <Hero />

        <div className={"flex items-center justify-center flex-wrap max-w-3xl"}>
          <Card
            href="https://nextjs.org/docs"
            title="Documentation"
            description="Find in-depth information about Next.js features and API."
          />
          <Card
            href="https://nextjs.org/learn"
            title="Learn"
            description="Learn about Next.js in an interactive course with quizzes!"
          />
          <Card
            href="https://github.com/vercel/next.js/tree/canary/examples"
            title="Examples"
            description="Discover and deploy boilerplate example Next.js projects."
          />
          <Card
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <Footer />
    </div>
  );
}
